# Generated by Django 4.2.8 on 2025-12-06 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mmsi",
                    models.CharField(
                        db_index=True,
                        help_text="Maritime Mobile Service Identity",
                        max_length=9,
                        unique=True,
                    ),
                ),
                (
                    "imo_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="International Maritime Organization Number",
                        max_length=7,
                        null=True,
                        unique=True,
                    ),
                ),
                ("vessel_name", models.CharField(db_index=True, max_length=100)),
                ("call_sign", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "vessel_type",
                    models.CharField(
                        choices=[
                            ("cargo", "Cargo Ship"),
                            ("tanker", "Tanker"),
                            ("passenger", "Passenger Ship"),
                            ("fishing", "Fishing Vessel"),
                            ("tug", "Tug Boat"),
                            ("military", "Military Vessel"),
                            ("sailing", "Sailing Vessel"),
                            ("other", "Other"),
                        ],
                        default="cargo",
                        max_length=50,
                    ),
                ),
                (
                    "flag_country",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code", max_length=2
                    ),
                ),
                ("built_year", models.IntegerField(blank=True, null=True)),
                ("gross_tonnage", models.IntegerField(blank=True, null=True)),
                (
                    "deadweight",
                    models.IntegerField(
                        blank=True, help_text="Deadweight Tonnage", null=True
                    ),
                ),
                (
                    "length_overall",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Length in meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "beam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Width in meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "draft",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Draft in meters",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("underway", "Underway Using Engine"),
                            ("at_anchor", "At Anchor"),
                            ("not_under_command", "Not Under Command"),
                            (
                                "restricted_maneuverability",
                                "Restricted Maneuverability",
                            ),
                            ("moored", "Moored"),
                            ("aground", "Aground"),
                            ("fishing", "Engaged in Fishing"),
                            ("under_sail", "Under Way Sailing"),
                        ],
                        default="underway",
                        max_length=50,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "speed_over_ground",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Speed in knots",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "course_over_ground",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Course in degrees",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "heading",
                    models.IntegerField(
                        blank=True, help_text="Heading in degrees", null=True
                    ),
                ),
                (
                    "destination",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "eta",
                    models.DateTimeField(
                        blank=True, help_text="Estimated Time of Arrival", null=True
                    ),
                ),
                ("last_position_update", models.DateTimeField(blank=True, null=True)),
                (
                    "data_source",
                    models.CharField(
                        default="manual",
                        help_text="Source of vessel data",
                        max_length=50,
                    ),
                ),
                (
                    "ais_update_frequency",
                    models.IntegerField(
                        default=60, help_text="AIS update frequency in seconds"
                    ),
                ),
                (
                    "is_tracked",
                    models.BooleanField(
                        default=True, help_text="Whether to track this vessel"
                    ),
                ),
                ("internal_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Vessel",
                "verbose_name_plural": "Vessels",
                "db_table": "vessels",
                "ordering": ["-last_position_update"],
            },
        ),
        migrations.CreateModel(
            name="VesselRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("route_name", models.CharField(max_length=200)),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                (
                    "waypoints",
                    models.JSONField(
                        default=list,
                        help_text="List of route waypoints as [lat, lon] pairs",
                    ),
                ),
                ("planned_departure", models.DateTimeField(blank=True, null=True)),
                ("planned_arrival", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_distance_nm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance in nautical miles",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="vessels.vessel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Route",
                "verbose_name_plural": "Vessel Routes",
                "db_table": "vessel_routes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VesselPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "speed_over_ground",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "course_over_ground",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("heading", models.IntegerField(blank=True, null=True)),
                (
                    "navigational_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Position timestamp from AIS"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When data was received by our system",
                    ),
                ),
                ("data_source", models.CharField(default="ais", max_length=50)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_history",
                        to="vessels.vessel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Position",
                "verbose_name_plural": "Vessel Positions",
                "db_table": "vessel_positions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="VesselNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_important", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vessel_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="vessels.vessel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Note",
                "verbose_name_plural": "Vessel Notes",
                "db_table": "vessel_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(
                fields=["mmsi", "is_deleted"], name="vessels_mmsi_1b27fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(
                fields=["vessel_type", "is_tracked"], name="vessels_vessel__a1547a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(
                fields=["last_position_update"], name="vessels_last_po_965032_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(
                fields=["latitude", "longitude"], name="vessels_latitud_a51002_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vesselroute",
            index=models.Index(
                fields=["vessel", "is_active"], name="vessel_rout_vessel__c346c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vesselroute",
            index=models.Index(
                fields=["created_by"], name="vessel_rout_created_b69893_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vesselposition",
            index=models.Index(
                fields=["vessel", "timestamp"], name="vessel_posi_vessel__372247_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vesselposition",
            index=models.Index(
                fields=["timestamp"], name="vessel_posi_timesta_3315cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vesselposition",
            index=models.Index(
                fields=["latitude", "longitude"], name="vessel_posi_latitud_f9c550_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vesselnote",
            index=models.Index(
                fields=["vessel", "created_at"], name="vessel_note_vessel__9fa9a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vesselnote",
            index=models.Index(
                fields=["user", "created_at"], name="vessel_note_user_id_f9c7e2_idx"
            ),
        ),
    ]
