# Generated by Django 4.2.8 on 2026-01-06 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vessels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VesselAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for assignment",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this assignment is currently active",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this assignment expires", null=True
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vessel_assignments_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vessel_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="vessels.vessel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Assignment",
                "verbose_name_plural": "Vessel Assignments",
                "db_table": "vessel_assignments",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="vessel_assi_user_id_718d31_idx",
                    ),
                    models.Index(
                        fields=["vessel", "is_active"],
                        name="vessel_assi_vessel__a043b3_idx",
                    ),
                ],
                "unique_together": {("user", "vessel")},
            },
        ),
    ]
